"""ugh

Revision ID: 322fbd183335
Revises: 5c8b01f87970
Create Date: 2023-05-18 06:52:21.815162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322fbd183335'
down_revision = '5c8b01f87970'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugs', sa.Column('symptoms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drugs', 'symptoms')
    # ### end Alembic commands ###
