"""ugh

Revision ID: 5c8b01f87970
Revises: f4c99c4af4b0
Create Date: 2023-05-18 06:49:48.338845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8b01f87970'
down_revision = 'f4c99c4af4b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drugs', 'symptoms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugs', sa.Column('symptoms', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
