"""l

Revision ID: f4c99c4af4b0
Revises: f2e019396861
Create Date: 2023-05-18 05:08:37.212085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c99c4af4b0'
down_revision = 'f2e019396861'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
